version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: cresters_frontend
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - REACT_APP_BASE_URI=https://cresters-user-service.herokuapp.com/